services:
  - type: web
    name: infi-testnet-rpc
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: INFI_DATA_DIR
        value: /home/infi/infi-data
